### ISSUE TITLE
Missing option codes

### ISSUE THREAD

**Issue by jswanner** [fredrikfjeld/tesla-options-decoder#1]
Hey @fredrikfjeld, this options decoder is pretty sweet.

But, of the 52 codes that are serialized in the `options` value of my "View Design" URL, only 45 are being displayed.

I noticed that the [codes are only displayed if they are known codes](https://github.com/fredrikfjeld/tesla-options-decoder/blob/gh-pages/script.js#L82) in the pricebook JSON files. Did you create these JSON files yourself, or did you get them from another source? I'm asking because I'd like to help with adding the extra codes, either by manually adding them or updating from whatever source you used.

A specific example of what I'd like to add is `BT70` for the new 70 kWh battery.

**Comment by dewski** [comment]
Is there a script that you used to fetch these? If so I'd be happy to setup a routine job to update the list.

**Comment by jswanner** [comment]
It looks like @fredrikfjeld has created one since I made the issue: https://github.com/fredrikfjeld/tesla-options-decoder/blob/gh-pages/get-pricebook.sh
