### ISSUE TITLE
get-pricebook.sh no longer works.

### ISSUE THREAD

**Issue by icdevin** [fredrikfjeld/tesla-options-decoder#3]
Hi,

First, thanks for sharing this on GitHub. I'm working on some Tesla-related application stuff and I wouldn't even know what I was looking at/for without this. The configuration/options was a bit intimidating so the help is much appreciated.

I noticed your script to fetch the pricebooks doesn't work anymore (not for me, anyway, reason unknown, perh). My solution isn't perfect but I did write a small script using PhantomJS [here](https://github.com/icdevin/node-tesla/blob/master/scripts/get-options.js) that gets the same data as in your pricebook data. I wanted to share mine in case you wanted to update your data files but didn't want to go through the hassle of updating the script.

Thanks again.

**Comment by fredrikfjeld** [comment]
Thanks a lot, I appreciate your effort! I'll definitely look into implementing your script.

I'm not actively developing these tools, but I find myself coming back to it from time to time.

**Comment by fredrikfjeld** [comment]
This was just fixed in the pull request #4 by @cameronr
